import "./globals.css";
import Navbar from "@/components/Utility/Navbar";


export const metadata = {
  title: "EventEase | Event Planning Made Easy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-blue-50 `}>
        <Navbar />
        <div className="text-sm px-2 md:px-0 md:text-xl  container m-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
